// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package hastebrot.playground.requery.modeljpa;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;
import javax.annotation.Generated;

@Generated("io.requery.processor.EntityProcessor")
public class Models {
    public static final EntityModel MODELJPA = new EntityModelBuilder("modeljpa")
    .addType(PhoneEntity.$TYPE)
    .addType(AddressEntity.$TYPE)
    .addType(GroupEntity.$TYPE)
    .addType(PersonEntity.$TYPE)
    .addType(GroupEntity_PersonEntity.$TYPE)
    .build();

    private Models() {
    }
}
